name: flutter_grades_checker
description: Web-based UNO promotional list to SMS Database grade cross-checker.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  excel: ^4.0.6
  file_picker: ^8.1.7
  http: ^1.2.2

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
